### ISSUE TITLE
Null users in DB

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattro#29]
I discovered some "null" users in the DB. This is the list of users one gets from the REST interface:

```json
[
  {
    "_id": "guest"
  },
  {
    "_id": "hampos"
  },
  {
    "_id": "anonymous"
  },
  {
    "_id": "Sopasakis"
  },
  null,
  null,
  null,
  null
]
```

and in the DB, one gets the following bizzare entries:

```
{ "_id" : ObjectId("5534af20926f4608d7affe2c"), "capabilities" : { "models" : 100, "algorithms" : 5, "tasksParallel" : 5, "substances" : 1000, "bibtex" : 100 }, "publicationRatePerWeek" : { "models" : 10, "algorithms" : 1, "substances" : 10, "bibtex" : 10 } }
{ "_id" : ObjectId("5534af26926f4608d7affe2d"), "capabilities" : { "models" : 100, "algorithms" : 5, "tasksParallel" : 5, "substances" : 1000, "bibtex" : 100 }, "publicationRatePerWeek" : { "models" : 10, "algorithms" : 1, "substances" : 10, "bibtex" : 10 } }
{ "_id" : ObjectId("5534af27926f4608d7affe2e"), "capabilities" : { "models" : 100, "algorithms" : 5, "tasksParallel" : 5, "substances" : 1000, "bibtex" : 100 }, "publicationRatePerWeek" : { "models" : 10, "algorithms" : 1, "substances" : 10, "bibtex" : 10 } }
{ "_id" : ObjectId("5534af28926f4608d7affe2f"), "capabilities" : { "models" : 100, "algorithms" : 5, "tasksParallel" : 5, "substances" : 1000, "bibtex" : 100 }, "publicationRatePerWeek" : { "models" : 10, "algorithms" : 1, "substances" : 10, "bibtex" : 10 } }
```
 I guess something is wrong with user registration.

**Comment by alphaville** [comment]
It seems that the SSO server when at high load returns this response with status 401:

```
<html><head><title>Apache Tomcat/7.0.19 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - Request: http://localhost:8180/opensso/identity/attributes
Exception: IOException: Server returned HTTP response code: 401 for URL: http://localhost:8180/opensso/identity/attributes
java.io.IOException: Server returned HTTP response code: 401 for URL: http://localhost:8180/opensso/identity/attributes
	at sun.reflect.GeneratedConstructorAccessor122.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1491)
	at java.security
```

We need to check whether the SSO service returns valid responses (even for valid tokens).

**Comment by alphaville** [comment]
Fixed (by the way, the SSO server is now responding as expected even under very high load.)
